.TH naming 5 "22.08.2024" "0.1" "meta archives"

.SH NAME

naming	\-	naming conventions for the meta archives

.SH INCANTATIONS

incantations(functions) are named based on the following format:
.TP
.B return	(st_)type_verb(detail)();

.TP
.B  st_
optional prefix to determine the scope of the function as static.
.TP
.B data
data type to be manipulated by the function.
.TP
.B verb
the action performed by the function to the data.
.TP
.B detail
optional extra specifications to the action performed.

.SH TYPE
Most types can act and be acted upon in simmilar ways.
execptions are noted.
.TP
.B
conjure: magical creatures that can be created and manipulated.
.TS
tab(|);
|l | l | l|.
_
CREATURE          |PROTOTYPE          |OVERVIEW          
_
serpent|srp(_type) |linearly linked list
ouroboros|oro(_type) |circularly linked list
coatl|ctl(_type) |doubly linked list
coatl oroboros|cro(_type) |doubly circularly linked list
_
Hydra|hyd(_type)|branching
_
Chimera|khi(_type(_type(...))|heterogeneous group
Golen|gln(_type)|homogeneous group
_
Sphinx|sph(_type)|queue
Minotaur|mtr(_type)|stack
_
.TE
Conjurations can be named as the collection name of the primitive they hold
(eg: veils, rune_book, constellation). In case the collection is heterogeneous,
creatures can be named as:

serpent, ouroboros:	echdina, typhon or jormungandr.

coatl:				Quetzalcoatl

.B
Primitives: basic types that serve a specific purpose
.TS
tab(|);
|r|c|c|l|.
_
PRIMITIVE|ABSTRACTION|NAMES|COLLECTION|
_
int|iterator|i, j, k|iters, itr
int|offset|veil|veils, vls
int|index|rune|rune_book, rbk
int|timestamp|kin|clock, clk
int|identifier|zodiac|constellation, cll
int|file descriptor|scroll|trove, trv
int|seed|seed|garden, grn
int, float|scalar|s, z, c|scalars, scl
int, float|coordinates|x, y, z|vector, vec
char|ascii|sigil|string, str
_
.TE
these variable names cover most cases, and, if needed, the names should hold suffixes
specifying and differentianing the varible,
(eg: rune_of_separation, scroll_of_map, seed_of_harmony)
