.TH str_hasChar 3 "September 20204" "1.0" "meta archives"
.SH NAME

str_hasChar	\-	Check string for char existance.

.SH SYNOPSIS

#include  <archives.h>

.B t_bool	str_hasChar(const char *str, char c)

.SH DESCRIPTION

Receives as a parameter a (char *)str, assumed to be a true C string, then iterates
it once, stopping at the first occurence of \fB(char)c\fP.

.SH RETURN VALUE

If there is at least one occurence of \fB(char)c\fP returns TRUE, else returns FALSE
